#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

autoload -Uz promptinit
promptinit
prompt steeef

bindkey "^[[1;3C" forward-word
bindkey "^[[1;3D" backward-word
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word

export WORKON_HOME=$HOME/envs
export PROJECT_HOME=$HOME/projects

# Source GDS aliases
. ~/.gds_aliases

# rbenv
eval "$(rbenv init -)"

#JAVA_HOME
export JAVA_HOME=$(/usr/libexec/java_home)

# Go lang PATH
export GOPATH=/Users/davidking/.gocode

# PATH
export PATH=/Applications/Postgres.app/Contents/Versions/9.4/bin:/Users/davidking/Library/elasticsearch-1.7.1/bin:/Users/davidking/Library/Python/2.7/bin:$GOPATH/bin:$PATH

